stages:
    - deploy

deploy_stage:
  tags:
    - lnf
  stage: deploy
  image: alpinelinux/ansible
  script:
    - apk add sshpass
    - cd ansible
    - ansible-playbook -i console_list.ini gitupdate.yaml
