<?xml version="1.0" encoding="UTF-8"?>
<databrowser>
  <title>Beam Energy Trend</title>
  <show_toolbar>true</show_toolbar>
  <scroll>true</scroll>
  <update_period>3.0</update_period>
  <scroll_step>5</scroll_step>
  <start>-5 minutes</start>
  <end>now</end>
  <axes>
    <axis>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>false</right>
      <color>
        <red>31</red>
        <green>73</green>
        <blue>125</blue>
      </color>
      <min>0.0</min>
      <max>200.0</max>
      <grid>true</grid>
      <autoscale>true</autoscale>
      <log_scale>false</log_scale>
    </axis>
    <axis>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>true</right>
      <color>
        <red>192</red>
        <green>80</green>
        <blue>77</blue>
      </color>
      <min>0.0</min>
      <max>200.0</max>
      <grid>false</grid>
      <autoscale>true</autoscale>
      <log_scale>false</log_scale>
    </axis>
    <axis>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>true</right>
      <color>
        <red>75</red>
        <green>172</green>
        <blue>198</blue>
      </color>
      <min>0.0</min>
      <max>200.0</max>
      <grid>false</grid>
      <autoscale>true</autoscale>
      <log_scale>false</log_scale>
    </axis>
  </axes>
  <pvlist>
    <pv>
      <display_name>E_kin [MeV]</display_name>
      <name>$(P):E_KIN</name>
      <axis>0</axis>
      <color>
        <red>31</red>
        <green>73</green>
        <blue>125</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <ring_size>5000</ring_size>
      <period>0.0</period>
      <request>OPTIMIZED</request>
      <visible>true</visible>
    </pv>
    <pv>
      <display_name>p [MeV/c]</display_name>
      <name>$(P):P</name>
      <axis>1</axis>
      <color>
        <red>192</red>
        <green>80</green>
        <blue>77</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <ring_size>5000</ring_size>
      <period>0.0</period>
      <request>OPTIMIZED</request>
      <visible>true</visible>
    </pv>
    <pv>
      <display_name>I_dip [A]</display_name>
      <name>$(P):I_DIP</name>
      <axis>2</axis>
      <color>
        <red>75</red>
        <green>172</green>
        <blue>198</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <ring_size>5000</ring_size>
      <period>0.0</period>
      <request>OPTIMIZED</request>
      <visible>true</visible>
    </pv>
  </pvlist>
</databrowser>
