---
- name: Perform update on Windows
  hosts: windows_hosts
  gather_facts: no
  tasks:
    - name: Disable host key checking
      set_fact:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - name: kill Phoebus if running
      shell: |
        @echo off
        setlocal enabledelayedexpansion
        set "found=0"
        for /f "tokens=*" %%A in ('jps ^| findstr "SNAPSHOT.jar"') do (
            for /f "tokens=1" %%B in ("%%A") do (
          set result=%%B
          if not "!result!"=="" (
                    echo !result!
                    echo "Trovato"
              Taskkill /PID !result!
                    set /a found+=1
                )
          )
        )
        endlocal
      ignore_errors: yes

    - name: Launch Powershell script
      shell: cd epik8-sparc/opi && powershell ./installPhoebusWindowsEnvironment.ps1

        

